### ISSUE TITLE
Big speed difference on Mac vs CentOS

### ISSUE THREAD

**Issue by danielhomer** [discord/lilliput#41] opened 2018-08-13 09:48 UTC
I've compiled the `examples/main.go` on both a MacBook Pro (Early 2015 i5) and CentOS (Amazon t2.large) and the OSX build is _much_ faster

Mac
```
time ./main-osx --input=tlou2ps4pro1.jpg --output=test123.webp                                                                        10:40:01
file type: JPEG
3840px x 2160px
image written to test123.webp
        1.20 real         1.10 user         0.07 sys
```

t2.large 
```
[ec2-user@ip-172-31-35-112 examples]$ time ./main --input=tlou2ps4pro1.jpg --output=test113.webp
file type: JPEG
3840px x 2160px
image written to test113.webp

real	0m8.039s
user	0m8.001s
sys	0m0.040s
```

Is there anything obvious I'm missing? I've tried the `build-deps-linux.sh` out of the box, as well as adding the following flags to the OpenCV cmake:
```
-DCMAKE_BUILD_TYPE=RELEASE -DWITH_TBB=ON -DWITH_IPP=ON -DWITH_V4L=ON -DENABLE_AVX=ON -DENABLE_SSSE3=ON -DENABLE_SSE41=ON -DENABLE_SSE42=ON -DENABLE_POPCNT=ON -DENABLE_FAST_MATH=ON -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF
```
But nothing is bringing it close to the Mac speed.

Cheers.

**Comment by brian-armstrong-discord** [comment] 2019-02-05 21:02
Hi @danielhomer 

I think this might have been due to a regression checked in here. Can you try again on the latest master?

**Comment by skidder** [comment] 2024-11-25 22:10
Closing this issue due to inactivity. Please feel free to reopen if this is still relevant and provide any updated information. Thank you for the report!

**Closed by skidder** 2024-11-25 22:10 UTC
